<a href="https://colab.research.google.com/github/gmauricio-toledo/Curso-Python-2023/blob/main/Notebooks/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div>
<img src="https://github.com/gmauricio-toledo/Curso-Python-2023/blob/main/Notebooks/img/numpy-logo.png?raw=1" width="800"/>
</div>

[NumPy](https://numpy.org/doc/stable/user/index.html#user) es el paquete fundamental para la computación científica en Python. Es una biblioteca de Python que proporciona un objeto de matriz multidimensional, varios objetos derivados y muchas rutinas para realizar operaciones rápidas con matrices, incluidas operaciones matemáticas, lógicas, de manipulación de formas, ordenación, selección, I/O, transformadas discretas de Fourier, álgebra lineal básica, operaciones estadísticas básicas, simulación aleatoria y mucho más.

Además, NumPy es usado ampliamente por otros módulos importantes de Python como Pandas, Scikit learn, TensorFlow, etc.

NumPy ofrece una enorme gama de formas rápidas y eficientes de crear arreglos y manipular datos numéricos dentro de ellos.

Mientras que una lista Python puede contener diferentes tipos de datos dentro de una misma lista, todos los elementos de un array NumPy deben ser homogéneos. Las operaciones matemáticas que se realizan sobre arrays serían extremadamente ineficientes si los arrays no fueran homogéneos.

Los arrays de NumPy son más rápidos y compactos que las listas de Python. Un array consume menos memoria y es cómodo de usar. NumPy utiliza mucha menos memoria para almacenar datos y proporciona un mecanismo de especificación de los tipos de datos. Esto permite optimizar aún más el código.

In [ ]:
import numpy

*Tradicionalmente* se importa así

In [2]:
import numpy as np

#Inicialización de arreglos `ndarray`

Una de las clases fundamentales y básicas de Numpy es el arreglo `numpy.array`. Este puede pensarse como un vector, matriz o tensor $n$-dimensional.

* **Vectores**: Arreglos unidimensionales de tamaño (*forma*) $(n,)$.
* **Matrices**: Arreglos bidimensionales de tamaño $(n,m)$. Son $n$ filas y $m$ columnas.

Se puede definir a partir de varios métodos o a partir de una lista de python. [Detalles](https://numpy.org/doc/stable/user/basics.creation.html)

**Ejemplo:** Definiendo un arreglo de numpy a partir de una lista de Python.

In [3]:
valores = [3,2,-3,5.5]

arreglo = np.array(valores)

print(arreglo)
print(type(arreglo))

[ 3.   2.  -3.   5.5]
<class 'numpy.ndarray'>


**Ejemplo:** Definiendo un arreglo de numpy de tamaño determinado lleno con ceros o unos.

In [6]:
arreglo_ceros = np.zeros(shape=(4,))
print(arreglo_ceros,end='\n\n')

matriz_unos = np.ones(shape=(3,2))
print(matriz_unos)

[0. 0. 0. 0.]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Una vez que tenemos un arreglo, podemos usar cualquiera de los métodos de un arreglo de numpy. Por ejemplo,

* La forma del arreglo:

In [ ]:
arreglo.shape

(4,)

* El número de dimensiones del arreglo

In [ ]:
arreglo.ndim

1

También podemos definir arreglos bidimensionales (matrices).

In [ ]:
valores = [[-1,1],[0,3],[2,-1],[0.5,-3]]

matriz = np.array(valores)

print(matriz)
print(f"Forma del arreglo: {matriz.shape}")
print(f"Dimensiones del arreglo: {matriz.ndim}")

[[-1.   1. ]
 [ 0.   3. ]
 [ 2.  -1. ]
 [ 0.5 -3. ]]
Forma del arreglo: (4, 2)
Dimensiones del arreglo: 2


Podemos acceder a los valores individuales del arreglo, renglones o filas.

**Recordar que en python enumeramos las secuencias como $0,1,2,...$ en lugar de $1,2,3,...$**

In [ ]:
entrada = matriz[1,0]
print(f"Elemento (2,1): {entrada}")

renglon = matriz[1]
renglon = matriz[1,:]
print(f"Renglón 2: {renglon}")

columna = matriz[:,0]
print(f"Columna 1: {columna}")

Elemento (2,1): 0.0
Renglón 2: [0. 3.]
Columna 1: [-1.   0.   2.   0.5]


✅ "Ventajas de numpy" operaciones con arreglos vs iteración

In [ ]:
v = np.array([-1,2,0,1])
w = np.array([3,1,-2,5])

v+w

## Ejemplo: Calcular errores

Definimos una función para calcular el error absoluto entre un valor real y una aproximación a este valor

In [ ]:
import numpy as np

def error_absoluto(real, aproximacion):
    return np.abs(real-aproximacion)

def error_relativo(real, aproximacion):
    '''
    Implementar la función
    '''
    pass  # instrucción para "dejar en blanco" el cuerpo de una función

Como ejemplo, consideremos el siguiente valor real y una secuencia de aproximaciones a dicho valor real

In [ ]:
valor_real = 4.5

aproximaciones = [2.5, 2.7, 3.1, 3.6, 3.9, 4.2, 4.6, 4.55]

Usando un ciclo `for` calculamos e imprimimos el error absoluto entre cada valor de la secuencia y el valor real

In [ ]:
for aprox in aproximaciones:
    print(f"Error absoluto: {error_absoluto(valor_real,aprox)}")
    # print(f"Error absoluto: {round(error_absoluto(valor_real,aprox),3)}")

Usando numpy podemos simplificar el proceso anterior y hacerlo más rápido. Esta es una de muchas ventajas de Numpy.

In [ ]:
aproximaciones = np.array(aproximaciones)

error_absoluto(valor_real, aproximaciones)

array([2.  , 1.8 , 1.4 , 0.9 , 0.6 , 0.3 , 0.1 , 0.05])